-- Oracle Database Schema for CRUD API
-- Run this script as DBA to create the application schema

-- Create user for the application (run as SYSTEM/DBA)
-- CREATE USER CRUD_USER IDENTIFIED BY your_password;
-- GRANT CONNECT, RESOURCE TO CRUD_USER;
-- GRANT CREATE SESSION TO CRUD_USER;
-- GRANT CREATE TABLE TO CRUD_USER;
-- GRANT CREATE SEQUENCE TO CRUD_USER;

-- Create PRODUCTS table
CREATE TABLE PRODUCTS (
    ID NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    PRICE NUMBER(18,2) NOT NULL,
    STOCK_QUANTITY NUMBER(10) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP
);

-- Create index for faster queries
CREATE INDEX IDX_PRODUCTS_IS_ACTIVE ON PRODUCTS(IS_ACTIVE);
CREATE INDEX IDX_PRODUCTS_CREATED_AT ON PRODUCTS(CREATED_AT);

-- Insert sample data
INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, STOCK_QUANTITY) VALUES ('Laptop', 'High-performance laptop', 999.99, 50);
INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, STOCK_QUANTITY) VALUES ('Mouse', 'Wireless mouse', 29.99, 200);
INSERT INTO PRODUCTS (NAME, DESCRIPTION, PRICE, STOCK_QUANTITY) VALUES ('Keyboard', 'Mechanical keyboard', 79.99, 100);

COMMIT;
